# These are supported funding model platforms

github: Axelaredz, Germenzi
custom: ['https://vk.com/donut/H360ru','https://boosty.to/ne6oru/donate','https://yoomoney.ru/to/410011134627436'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
